import * as Browser from 'webextension-polyfill'

let titleElement = null
let button: HTMLImageElement = null

const intervalID = setInterval(async () => {
    titleElement = document.querySelector('h1.title > yt-formatted-string')
    const info = document.querySelector(
        'div#info.style-scope.ytd-video-primary-info-renderer'
    )
    const menuContainer = document.querySelector('#menu-container')
    let songTitle = titleElement?.innerHTML

    if (songTitle) {
        const div = document.createElement('div')
        div.id = 'open-on-genius-div'

        button = document.createElement('img')
        button.src = Browser.runtime.getURL('images/genius.png')
        button.id = 'open-on-genius-button'

        const openText = document.createElement('span')
        openText.textContent = 'Open on Genius'
        openText.id = 'open-on-genius-text'

        div.appendChild(button)
        div.appendChild(openText)
        div.onclick = async () => {
            let artistName = undefined
            if (
                document
                    .querySelector('div.ytd-video-secondary-info-renderer#description')
                    .innerHTML.includes('Auto-generated by YouTube.')
            ) {
                artistName = document.querySelector('ytd-channel-name a').innerHTML
            }
            await Browser.runtime.sendMessage({
                songTitle,
                ...(artistName && { artistName }),
            })

            button.classList.add('spinning')
        }

        titleElement.parentNode.appendChild(div)

        new MutationObserver(() => {
            songTitle = titleElement?.innerHTML
        }).observe(titleElement, {
            subtree: true,
            childList: true,
        })

        clearInterval(intervalID)
    }
}, 200)

Browser.runtime.onMessage.addListener((message) => {
    console.log(message)
    if (message?.shake) {
        const div = document.querySelector('#open-on-genius-div')
        div.classList.add('shaking')
        setTimeout(() => {
            div.classList.remove('shaking')
        }, 1000)
    } else if (message?.stopSpin) {
        button.classList.remove('spinning')
    }
})
