# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint + Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        uses: icrawl/action-eslint@v1

      - name: Build
        run: npm run build

      - name: Zip
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist.zip dist

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: dist.zip
          path: dist.zip


  release:
    needs: ['build']
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest"
          message: "Latest release"
          force_push_tag: true

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist.zip.zip'
          omitBody: true
          tag: latest
          artifactContentType: application/zip
